### ISSUE TITLE
add metadata to certificates

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-security#49]
Per meeting discussion, we should add the following metadata to user certificates:
```toml
algorithm = "ed25519"
issuer = "uuid-of-ca-cert"
domain = "hype.llnl.gov"
```

**Comment by garlick** [comment]
These fields suggested themselves after a review of [X.509](https://en.wikipedia.org/wiki/X.509), which are structured thus:

* Certificate
  * Version Number
  * Serial Number
  * Signature Algorithm ID
  * Issuer Name
  * Validity period
     * Not Before
     * Not After
  * Subject name
  * Subject Public Key Info
    * Public Key Algorithm
    * Subject Public Key
  * Issuer Unique Identifier (optional)
  * Subject Unique Identifier (optional)
  * Extensions (optional)
     * ...
* Certificate Signature Algorithm
* Certificate Signature

**Comment by garlick** [comment]
To summarize the current metadata (after #53), this is an example CA cert (self-signed):
```toml
[metadata]
    algorithm = "ed25519"
    uuid = "98c7b622-bec6-4051-8fbe-4ac59c445566"
    ctime = 2018-02-16T18:04:20Z
    xtime = 2018-02-16T18:05:20Z
    userid = 5588
    max-sign-ttl = 30
    issuer = "98c7b622-bec6-4051-8fbe-4ac59c445566"
    domain = "EXAMPLE.TEST"

[curve]
    public-key = "PZcyonj1B1Lr5Y63DFOiRupsKxHP5bdjJgYmHhhrHwg="
    signature = "fCKqHB0zSLYnl+r96REmAO9ZttPzrADmxwrd0p0oJT9GauQaPl+qaFEsxR91OM9AkNdgMUW18nyyMRIHy3cnAQ=="
```
and this is an example user cert signed by the above
```toml
[metadata]
    algorithm = "ed25519"
    uuid = "cc35ef8f-862f-4ecf-84df-277ce66a50fd"
    ctime = 2018-02-16T18:04:20Z
    xtime = 2018-02-16T18:05:20Z
    userid = 5588
    max-sign-ttl = 30
    issuer = "98c7b622-bec6-4051-8fbe-4ac59c445566"
    domain = "EXAMPLE.TEST"

[curve]
    public-key = "V+LAo5F8XinpEV4MfZNVWNlRbVnbJwO9vAirK6qM07A="
    signature = "nJm/+9tCq5eK/xKReUSVJCtrnM4umtYUILMcS+B7uvMkjIM5RGnDcWEq2OD7UQ/iUVkb/eqX62c0Drw1MzyGAQ=="
```
