### ISSUE TITLE
need certificate format

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-security#7]
It's useful to have a certificate format to store user's public and private keys.

In our prototype imp, we used a derivative of czmq's [zcert](http://czmq.zeromq.org/manual:zcert) certificates, but those are dependent on libczmq and we probably don't want to link with that.  The certs look like this

public key:
```
#   ****  Generated on 2017-04-05 13:37:15 by CZMQ  ****
#   ZeroMQ CURVE Public Certificate
#   Exchange securely, or use a secure mechanism to verify the contents
#   of this file after exchange. Store public certificates in your home
#   directory, in the .curve subdirectory.

metadata
    time = "2017-04-05T13:37:15"
    role = "signature"
curve
    public-key = "fyAQm1uvTk!SPm@cN2=U5W1mJJmK3{X:@N?g(t4W"
```

private key (secret-key redacted):
```
#   ****  Generated on 2017-04-05 13:37:15 by CZMQ  ****
#   ZeroMQ CURVE **Secret** Certificate
#   DO NOT PROVIDE THIS FILE TO OTHER USERS nor change its permissions.

metadata
    time = "2017-04-05T13:37:15"
    role = "signature"
curve
    public-key = "fyAQm1uvTk!SPm@cN2=U5W1mJJmK3{X:@N?g(t4W"
    secret-key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

**Comment by garlick** [comment]
TOML seems like a nice fit here, e.g. the above would be
```toml
[metadata]
    time = 2017-04-05T13:37:15
    role = "signature"
[curve]
    public-key = "fyAQm1uvTk!SPm@cN2=U5W1mJJmK3{X:@N?g(t4W"
```
```toml
[metadata]
    time = 2017-04-05T13:37:15
    role = "signature"
[curve]
    public-key = "fyAQm1uvTk!SPm@cN2=U5W1mJJmK3{X:@N?g(t4W"
    secret-key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by garlick** [comment]
One idea we had discussed was using an IMP key-pair to sign/verify user public key certs, so they can be sent along with signed requests.  The advantage is then verification only needs access to the IMP public key and a revocation list, not the full set of user public keys.

We need to figure out what a signed cert looks like (compared to above), and have a strategy for converting it to JSON and back so it can be enclosed in a message without invalidating the signature.

I think this is actually a much easier problem than the general JSON signing (or hypothetical TOML signing) one, since the certificate content can be well defined.  E.g. instead of needing to canonicalize an arbitrary TOML table to sign/verify it, we just need a way to create a certificate object from TOML or JSON, and then internally serialize _that_ in some repeatable way.

**Comment by garlick** [comment]
Hmm, I guess the "ca" could just tack on a section, e.g. (totally winging it about what might be required in there):

```toml
[metadata]
    time = 2017-04-05T13:37:15
    role = "signature"
    version = "1"
[curve]
    public-key = "fyAQm1uvTk!SPm@cN2=U5W1mJJmK3{X:@N?g(t4W"
[ca]
    time = 2017-04-05T13:37:15
    expiration = 2017-08-05T13:37:15
    userid = 5588
    hostname = "hype342"
    realm = "hype.llnl.gov"
    signature = "ed25519-ffncnpulos87Bs21RtxiXmZE9J66cFKeSo="
```
